[build]
builder = "dockerfile"
dockerfilePath = "backend/IsekaiDesnecessario.API/Dockerfile"
dockerContext = "."

[deploy]
startCommand = "dotnet IsekaiDesnecessario.API.dll"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
