// <auto-generated />
using System;
using IsekaiDesnecessario.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IsekaiDesnecessario.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623044113_PerfilPrincipal")]
    partial class PerfilPrincipal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BomHabitoClasse", b =>
                {
                    b.Property<int>("BomHabitoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassesId")
                        .HasColumnType("integer");

                    b.HasKey("BomHabitoId", "ClassesId");

                    b.HasIndex("ClassesId");

                    b.ToTable("BomHabitoClasse");
                });

            modelBuilder.Entity("ClasseMauHabito", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("integer");

                    b.Property<int>("MauHabitoId")
                        .HasColumnType("integer");

                    b.HasKey("ClassesId", "MauHabitoId");

                    b.HasIndex("MauHabitoId");

                    b.ToTable("ClasseMauHabito");
                });

            modelBuilder.Entity("ClasseMissao", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("integer");

                    b.Property<int>("MissaoId")
                        .HasColumnType("integer");

                    b.HasKey("ClassesId", "MissaoId");

                    b.HasIndex("MissaoId");

                    b.ToTable("ClasseMissao");
                });

            modelBuilder.Entity("ClasseRecompensa", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("integer");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("integer");

                    b.HasKey("ClassesId", "RecompensaId");

                    b.HasIndex("RecompensaId");

                    b.ToTable("ClasseRecompensa");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Atributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Atributos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#58a6ff",
                            Descricao = "Estudar, fazer cursos, resolver exercícios",
                            Emoji = "🧠",
                            Nome = "Inteligência"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#bc8cff",
                            Descricao = "Ler livros, podcasts, reflexão",
                            Emoji = "📚",
                            Nome = "Sabedoria"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#3fb950",
                            Descricao = "Treinar, academia, exercícios físicos",
                            Emoji = "💪",
                            Nome = "Físico"
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#f78166",
                            Descricao = "Tarefas domésticas, rotina, pontualidade",
                            Emoji = "⚙️",
                            Nome = "Disciplina"
                        },
                        new
                        {
                            Id = 5,
                            Cor = "#ffd700",
                            Descricao = "Pomodoro, sem celular, deep work",
                            Emoji = "🎯",
                            Nome = "Foco"
                        },
                        new
                        {
                            Id = 6,
                            Cor = "#f85149",
                            Descricao = "Sono, hidratação, dieta, pausas",
                            Emoji = "❤️",
                            Nome = "Vitalidade"
                        });
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.BomHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtributoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Global");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Habito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Aprovado");

                    b.Property<int>("TravaDias")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.ToTable("BonsHabitos");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtributoId")
                        .HasColumnType("integer");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFeminino")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtributoId = 1,
                            Emoji = "🧙",
                            Nome = "Mago",
                            NomeFeminino = "Maga"
                        },
                        new
                        {
                            Id = 2,
                            AtributoId = 2,
                            Emoji = "🎵",
                            Nome = "Bardo",
                            NomeFeminino = "Barda"
                        },
                        new
                        {
                            Id = 3,
                            AtributoId = 3,
                            Emoji = "⚔️",
                            Nome = "Guerreiro",
                            NomeFeminino = "Guerreira"
                        },
                        new
                        {
                            Id = 4,
                            AtributoId = 4,
                            Emoji = "🛡️",
                            Nome = "Escudeiro",
                            NomeFeminino = "Escudeira"
                        },
                        new
                        {
                            Id = 5,
                            AtributoId = 5,
                            Emoji = "🎯",
                            Nome = "Executor",
                            NomeFeminino = "Executora"
                        },
                        new
                        {
                            Id = 6,
                            AtributoId = 6,
                            Emoji = "✨",
                            Nome = "Clérigo",
                            NomeFeminino = "Clériga"
                        });
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.DiarioAcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("DiarioAcoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Experimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Convertido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DuracaoDias")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Experimentos");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.ExperimentoDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExperimentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentoId");

                    b.ToTable("ExperimentosDia");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.HistoricoXp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("Moedas")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("XpHoje")
                        .HasColumnType("integer");

                    b.Property<string>("XpPorHoraJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("HistoricoXp");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.ItemInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("Preco")
                        .HasColumnType("integer");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.MauHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtributoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Global");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Habito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Aprovado");

                    b.Property<int>("TravaDias")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.ToTable("MausHabitos");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Missao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtributoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Global");

                    b.Property<int?>("MissaoPrincipalId")
                        .HasColumnType("integer");

                    b.Property<int>("RecompensaMoedas")
                        .HasColumnType("integer");

                    b.Property<int>("RecompensaXp")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Aprovado");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TravaDias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("TipoId");

                    b.ToTable("Missoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Lida");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClasseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataXpHoje")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DesafioConcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DesafioRecusadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<int>("Moedas")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PrincipalDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProximoNivelXp")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimaLootbox")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.Property<int>("XpHoje")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.PerfilBomHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("BomHabitoId")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("Streak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TravadoAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimaExecucao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BomHabitoId");

                    b.HasIndex("PerfilId", "BomHabitoId")
                        .IsUnique();

                    b.ToTable("PerfilBonsHabitos");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.PerfilMauHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("MauHabitoId")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("Streak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TravadoAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimaExecucao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MauHabitoId");

                    b.HasIndex("PerfilId", "MauHabitoId")
                        .IsUnique();

                    b.ToTable("PerfilMausHabitos");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.PerfilMissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Concluida")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MissaoId")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("Streak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TravadoAte")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MissaoId");

                    b.HasIndex("PerfilId", "MissaoId")
                        .IsUnique();

                    b.ToTable("PerfilMissoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.PerfilRecompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TravadoAte")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecompensaId");

                    b.HasIndex("PerfilId", "RecompensaId")
                        .IsUnique();

                    b.ToTable("PerfilRecompensas");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int?>("AtributoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Global");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PontosNecessarios")
                        .HasColumnType("integer");

                    b.Property<int>("Preco")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Aprovado");

                    b.Property<int>("TravaDias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.ToTable("Recompensas");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.SnapshotAtributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtributoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("PerfilId");

                    b.ToTable("SnapshotsAtributo");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.TipoMissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposMissao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Principal"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Secundária"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Desafio"
                        });
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Usuario");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BomHabitoClasse", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.BomHabito", null)
                        .WithMany()
                        .HasForeignKey("BomHabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.Classe", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClasseMauHabito", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Classe", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.MauHabito", null)
                        .WithMany()
                        .HasForeignKey("MauHabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClasseMissao", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Classe", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.Missao", null)
                        .WithMany()
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClasseRecompensa", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Classe", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.Recompensa", null)
                        .WithMany()
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.BomHabito", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany("BonsHabitos")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atributo");

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Classe", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.DiarioAcao", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Experimento", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.ExperimentoDia", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Experimento", "Experimento")
                        .WithMany("Dias")
                        .HasForeignKey("ExperimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experimento");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.HistoricoXp", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("HistoricoXp")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.ItemInventario", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("Inventario")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.MauHabito", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany("MausHabitos")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atributo");

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Missao", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany("Missoes")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.TipoMissao", "Tipo")
                        .WithMany("Missoes")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("CriadoPor");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Notificacao", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Perfil", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Classe", "Classe")
                        .WithMany("Perfis")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Usuario", "Usuario")
                        .WithMany("Perfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Classe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.PerfilBomHabito", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.BomHabito", "BomHabito")
                        .WithMany("Ativacoes")
                        .HasForeignKey("BomHabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("BonsHabitos")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomHabito");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.PerfilMauHabito", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.MauHabito", "MauHabito")
                        .WithMany("Ativacoes")
                        .HasForeignKey("MauHabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("MausHabitos")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MauHabito");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.PerfilMissao", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Missao", "Missao")
                        .WithMany("Ativacoes")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("Missoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Missao");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.PerfilRecompensa", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("Recompensas")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.Recompensa", "Recompensa")
                        .WithMany("Ativacoes")
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Recompensa");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Recompensa", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atributo");

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.SnapshotAtributo", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Atributo", b =>
                {
                    b.Navigation("BonsHabitos");

                    b.Navigation("MausHabitos");

                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.BomHabito", b =>
                {
                    b.Navigation("Ativacoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Classe", b =>
                {
                    b.Navigation("Perfis");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Experimento", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.MauHabito", b =>
                {
                    b.Navigation("Ativacoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Missao", b =>
                {
                    b.Navigation("Ativacoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Perfil", b =>
                {
                    b.Navigation("BonsHabitos");

                    b.Navigation("HistoricoXp");

                    b.Navigation("Inventario");

                    b.Navigation("MausHabitos");

                    b.Navigation("Missoes");

                    b.Navigation("Recompensas");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Recompensa", b =>
                {
                    b.Navigation("Ativacoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.TipoMissao", b =>
                {
                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Usuario", b =>
                {
                    b.Navigation("Perfis");
                });
#pragma warning restore 612, 618
        }
    }
}
