// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using IsekaiDesnecessario.API.Data;

#nullable disable

namespace IsekaiDesnecessario.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Atributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Atributos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#58a6ff",
                            Descricao = "Estudar, fazer cursos, resolver exercícios",
                            Emoji = "🧠",
                            Nome = "Inteligência"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#bc8cff",
                            Descricao = "Ler livros, podcasts, reflexão",
                            Emoji = "📚",
                            Nome = "Sabedoria"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#3fb950",
                            Descricao = "Treinar, academia, exercícios físicos",
                            Emoji = "💪",
                            Nome = "Físico"
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#f78166",
                            Descricao = "Tarefas domésticas, rotina, pontualidade",
                            Emoji = "⚙️",
                            Nome = "Disciplina"
                        },
                        new
                        {
                            Id = 5,
                            Cor = "#ffd700",
                            Descricao = "Pomodoro, sem celular, deep work",
                            Emoji = "🎯",
                            Nome = "Foco"
                        },
                        new
                        {
                            Id = 6,
                            Cor = "#f85149",
                            Descricao = "Sono, hidratação, dieta, pausas",
                            Emoji = "❤️",
                            Nome = "Vitalidade"
                        });
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.BomHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtributoId")
                        .HasColumnType("int");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaExecucao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("PerfilId");

                    b.ToTable("BonsHabitos");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtributoId")
                        .HasColumnType("int");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFeminino")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtributoId = 1,
                            Emoji = "🧙",
                            Nome = "Mago",
                            NomeFeminino = "Maga"
                        },
                        new
                        {
                            Id = 2,
                            AtributoId = 2,
                            Emoji = "🎵",
                            Nome = "Bardo",
                            NomeFeminino = "Barda"
                        },
                        new
                        {
                            Id = 3,
                            AtributoId = 3,
                            Emoji = "⚔️",
                            Nome = "Guerreiro",
                            NomeFeminino = "Guerreira"
                        },
                        new
                        {
                            Id = 4,
                            AtributoId = 4,
                            Emoji = "🛡️",
                            Nome = "Escudeiro",
                            NomeFeminino = "Escudeira"
                        },
                        new
                        {
                            Id = 5,
                            AtributoId = 5,
                            Emoji = "🎯",
                            Nome = "Executor",
                            NomeFeminino = "Executora"
                        },
                        new
                        {
                            Id = 6,
                            AtributoId = 6,
                            Emoji = "✨",
                            Nome = "Clérigo",
                            NomeFeminino = "Clériga"
                        });
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.DiarioAcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("DiarioAcoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Experimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<bool>("Convertido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracaoDias")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Experimentos");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.ExperimentoDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperimentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentoId");

                    b.ToTable("ExperimentosDia");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.HistoricoXp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("Moedas")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("XpHoje")
                        .HasColumnType("int");

                    b.Property<string>("XpPorHoraJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("HistoricoXp");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.ItemInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("Preco")
                        .HasColumnType("int");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("int");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.MauHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtributoId")
                        .HasColumnType("int");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaExecucao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("PerfilId");

                    b.ToTable("MausHabitos");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Missao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtributoId")
                        .HasColumnType("int");

                    b.Property<bool>("Concluida")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MissaoPrincipalId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("RecompensaMoedas")
                        .HasColumnType("int");

                    b.Property<int>("RecompensaXp")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("PerfilId");

                    b.HasIndex("TipoId");

                    b.ToTable("Missoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClasseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataXpHoje")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DesafioConcluídoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DesafioRecusadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Moedas")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProximoNivelXp")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimaLootbox")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.Property<int>("XpHoje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<int?>("AtributoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PontosNecessarios")
                        .HasColumnType("int");

                    b.Property<int>("Preco")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("PerfilId");

                    b.ToTable("Recompensas");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.SnapshotAtributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtributoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("PerfilId");

                    b.ToTable("SnapshotsAtributo");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.TipoMissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposMissao");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("bit");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.BomHabito", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany("BonsHabitos")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("BonsHabitos")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Classe", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.DiarioAcao", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Experimento", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.ExperimentoDia", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Experimento", "Experimento")
                        .WithMany("Dias")
                        .HasForeignKey("ExperimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experimento");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.HistoricoXp", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("HistoricoXp")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.ItemInventario", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("Inventario")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.MauHabito", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany("MausHabitos")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("MausHabitos")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Missao", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany("Missoes")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("Missoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.TipoMissao", "Tipo")
                        .WithMany("Missoes")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Perfil");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Perfil", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Classe", "Classe")
                        .WithMany("Perfis")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Usuario", "Usuario")
                        .WithMany("Perfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Classe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Recompensa", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany("Recompensas")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.SnapshotAtributo", b =>
                {
                    b.HasOne("IsekaiDesnecessario.API.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsekaiDesnecessario.API.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Atributo", b =>
                {
                    b.Navigation("BonsHabitos");

                    b.Navigation("MausHabitos");

                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Classe", b =>
                {
                    b.Navigation("Perfis");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Experimento", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Perfil", b =>
                {
                    b.Navigation("BonsHabitos");

                    b.Navigation("HistoricoXp");

                    b.Navigation("Inventario");

                    b.Navigation("MausHabitos");

                    b.Navigation("Missoes");

                    b.Navigation("Recompensas");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.TipoMissao", b =>
                {
                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("IsekaiDesnecessario.API.Models.Usuario", b =>
                {
                    b.Navigation("Perfis");
                });
#pragma warning restore 612, 618
        }
    }
}
